services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: netmovies_development
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    env_file:
      - .env
    restart: always
    command: bash -c "bin/rails db:create db:migrate && bin/rails server -b 0.0.0.0 -p 3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - bundle_data:/rails/vendor/bundle

  sidekiq:
    build: .
    env_file:
      - .env
    command: bundle exec sidekiq
    depends_on:
      - redis
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/rails
      - bundle_data:/rails/vendor/bundle

volumes:
  db_data:
  bundle_data:
  redis_data:
